/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package space.engine;
import space.engine.util.SmallIntSet;
import static space.engine.Resource.*;
/**
 *
 * @author karol
 */
public class TechTree {
	public static Technology[] TREE;
	public static final int
			TECH_COUNT = 83;
	public static final int
		UNIVERSAL_CURE = 0,
		XENOECOLOGY = 1,
		ADVANCED_ABSTRACT_ALGEBRA = 2,
		ADVANCED_AGRICULTURE = 3,
		ADVANCED_ALLOYS = 4,
		ADVANCED_BIOLOGY = 5,
		ADVANCED_CHEMISTRY = 6,
		ADVANCED_EXPERT_SYSTEMS = 7,
		ADVANCED_LASERS = 8,
		ADVANCED_MILITARY_ALGORITHMS = 9,
		ADVANCED_NANOSTRUCTURES = 10,
		ADVANCED_NEUTRINO_GUN = 11,
		ADVANCED_NUMERICAL_ANALYSIS = 12,
		ADVANCED_PHOTON_DEFLECTORS = 13,
		AI_GOVERNMENT = 14,
		ANTI_PHOTON_SHIELDS = 15,
		ANYTHING_ANYWHERE_FUSION = 16,
		ARTIFICIAL_BODY = 17,
		ASTEROID_MINING = 18,
		BIOQUANTUM_MIND = 19,
		BIOSIMULATIONS = 20,
		CLIMATE_MANIPULATION = 21,
		COUNTERLASER = 22,
		COUNTER_NEUTRINO_GUN = 23,
		CYBERIMPLANTS = 24,
		ENGINEERING_SINGULARITY = 25,
		ENTROPY_CONTROL = 26,
		FRACTAL_MATERIALS = 27,
		GAIA = 28,
		GENETIC_ENGINEERING = 29,
		GENETIC_THERAPY = 30,
		GRAVITON_COLLECTOR = 31,
		GRAVITON_DETECTOR = 32,
		HADRON_COLLECTOR = 33,
		HEAVY_NUCLEAR_FUSION = 34,
		HIGGS_BOSON_DETECTOR = 35,
		HUMAN_LIKE_AI = 36,
		INTERGALACTIC_COLONIZATION = 37,
		INTERSTELLAR_PHILOSOPHY = 38,
		INVISIBILITY = 39,
		LEPTON_COLLECTOR = 40,
		LONGEVITY = 41,
		MATHEMATICAL_ETHICS = 42,
		MESON_COLLECTOR = 43,
		MILITARY_ALGORITHMS = 44,
		MULTIDIMENSIONAL_UNIFICATION_THEORY = 45,
		NANOBOTS = 46,
		NEUTRINO_COLLECTOR = 47,
		NEUTRINO_DRIVE = 48,
		NEUTRINO_GUN = 49,
		NEUTRINO_TELESCOPE = 50,
		NUCLEAR_FUSION = 51,
		PERFECT_HEAT_DIFFUSION = 52,
		PERFECT_HEAT_RADIATION = 53,
		PERFECT_MILITARY_ALGORITHMS = 54,
		PHOTON_BALLISTICS = 55,
		PHOTON_COLLECTOR = 56,
		PHOTON_COMPUTERS = 57,
		PLANETARY_DEFENSE = 58,
		PLANETLESS_COLONIES = 59,
		PORTABLE_NUCLEAR_FUSION = 60,
		QUANTUM_AI = 61,
		QUANTUM_COMPUTERS = 62,
		QUANTUM_CRYPTOGRAPHY = 63,
		QUANTUM_ETHICS = 64,
		QUANTUM_GOVERNMENT = 65,
		QUANTUM_GRAVITY_THEORY = 66,
		QUICK_HEAT_DIFFUSION = 67,
		QUICK_HEAT_RADIATION = 68,
		RELIGIOUS_TOLERANCE = 69,
		RIGOROUS_SCIENCE = 70,
		ROBOCULTURE = 71,
		ROBOETHICS = 72,
		ROBOTIC_COLONIES = 73,
		SCIENTIFICAL_SINGULARITY = 74,
		SENTIENT_AI = 75,
		SILICON_SUPERCOMPUTERS = 76,
		SOLVED_ETHICS = 77,
		STARDUST_GATHERING = 78,
		SUBATOMIC_PHOTON_DETECTOR = 79,
		SUPERCONDUCTORS = 80,
		SUPERSTITION_ERADICATION = 81,
		TERRAFORMING = 82;

	static{
		//TREE=new Technology[SmallIntSet.MAX_SIZE];
		TREE=new Technology[83];
		TREE[ADVANCED_ABSTRACT_ALGEBRA]=new Technology("ADVANCED_ABSTRACT_ALGEBRA",ZERO_RESOURCES);
		TREE[ADVANCED_AGRICULTURE]=new Technology("ADVANCED_AGRICULTURE",ZERO_RESOURCES, ADVANCED_BIOLOGY);
		TREE[ADVANCED_ALLOYS]=new Technology("ADVANCED_ALLOYS",ZERO_RESOURCES,ADVANCED_CHEMISTRY);
		TREE[ADVANCED_BIOLOGY]=new Technology("ADVANCED_BIOLOGY",ZERO_RESOURCES,GENETIC_ENGINEERING);
		TREE[ADVANCED_CHEMISTRY]=new Technology("ADVANCED_CHEMISTRY",ZERO_RESOURCES);
		TREE[ADVANCED_EXPERT_SYSTEMS]=new Technology("ADVANCED_EXPERT_SYSTEMS",ZERO_RESOURCES,ADVANCED_ABSTRACT_ALGEBRA,RIGOROUS_SCIENCE);
		TREE[ADVANCED_LASERS]=new Technology("ADVANCED_LASERS",ZERO_RESOURCES,SUPERCONDUCTORS);
		TREE[ADVANCED_MILITARY_ALGORITHMS]=new Technology("ADVANCED_MILITARY_ALGORITHMS",ZERO_RESOURCES,ADVANCED_NUMERICAL_ANALYSIS,MILITARY_ALGORITHMS,PHOTON_COMPUTERS);
		TREE[ADVANCED_NANOSTRUCTURES]=new Technology("ADVANCED_NANOSTRUCTURES",ZERO_RESOURCES);
		TREE[ADVANCED_NEUTRINO_GUN]=new Technology("ADVANCED_NEUTRINO_GUN",ZERO_RESOURCES,NEUTRINO_GUN,NEUTRINO_TELESCOPE);
		TREE[ADVANCED_NUMERICAL_ANALYSIS]=new Technology("ADVANCED_NUMERICAL_ANALYSIS",ZERO_RESOURCES,SILICON_SUPERCOMPUTERS);
		TREE[ADVANCED_PHOTON_DEFLECTORS]=new Technology("ADVANCED_PHOTON_DEFLECTORS",ZERO_RESOURCES,ADVANCED_ALLOYS,SUBATOMIC_PHOTON_DETECTOR);
		TREE[AI_GOVERNMENT]=new Technology("AI_GOVERNMENT",ZERO_RESOURCES,ADVANCED_EXPERT_SYSTEMS,ADVANCED_NUMERICAL_ANALYSIS,HUMAN_LIKE_AI,SOLVED_ETHICS);
		TREE[ANTI_PHOTON_SHIELDS]=new Technology("ANTI_PHOTON_SHIELDS",ZERO_RESOURCES,ADVANCED_NANOSTRUCTURES);
		TREE[ANYTHING_ANYWHERE_FUSION]=new Technology("ANYTHING_ANYWHERE_FUSION",ZERO_RESOURCES,HEAVY_NUCLEAR_FUSION,PORTABLE_NUCLEAR_FUSION);
		TREE[ARTIFICIAL_BODY]=new Technology("ARTIFICIAL_BODY",ZERO_RESOURCES,CYBERIMPLANTS,LONGEVITY);
		TREE[ASTEROID_MINING]=new Technology("ASTEROID_MINING",ZERO_RESOURCES);

		TREE[BIOQUANTUM_MIND]=new Technology("BIOQUANTUM_MIND",ZERO_RESOURCES,ARTIFICIAL_BODY,UNIVERSAL_CURE,QUANTUM_ETHICS);
		TREE[BIOSIMULATIONS]=new Technology("BIOSIMULATIONS",ZERO_RESOURCES,ADVANCED_NUMERICAL_ANALYSIS);

		TREE[CLIMATE_MANIPULATION]=new Technology("CLIMATE_MANIPULATION",ZERO_RESOURCES,ADVANCED_CHEMISTRY);
		TREE[COUNTERLASER]=new Technology("COUNTERLASER",ZERO_RESOURCES,ADVANCED_PHOTON_DEFLECTORS,PHOTON_BALLISTICS);
		TREE[COUNTER_NEUTRINO_GUN]=new Technology("COUNTER_NEUTRINO_GUN",ZERO_RESOURCES,COUNTERLASER,NEUTRINO_GUN,NEUTRINO_TELESCOPE);
		TREE[CYBERIMPLANTS]=new Technology("CYBERIMPLANTS",ZERO_RESOURCES,NANOBOTS,RELIGIOUS_TOLERANCE);

		TREE[ENGINEERING_SINGULARITY]=new Technology("ENGINEERING_SINGULARITY",ZERO_RESOURCES,ANYTHING_ANYWHERE_FUSION,QUANTUM_AI);
		TREE[ENTROPY_CONTROL]=new Technology("ENTROPY_CONTROL",ZERO_RESOURCES,GRAVITON_COLLECTOR,PERFECT_HEAT_DIFFUSION,PERFECT_HEAT_RADIATION,SCIENTIFICAL_SINGULARITY);

		TREE[FRACTAL_MATERIALS]=new Technology("FRACTAL_MATERIALS",ZERO_RESOURCES,ADVANCED_ALLOYS,ADVANCED_NANOSTRUCTURES);

		TREE[GAIA]=new Technology("GAIA",ZERO_RESOURCES,BIOQUANTUM_MIND,ENTROPY_CONTROL,QUANTUM_GOVERNMENT,ROBOTIC_COLONIES);
		TREE[GENETIC_ENGINEERING]=new Technology("GENETIC_ENGINEERING",ZERO_RESOURCES);
		TREE[GENETIC_THERAPY]=new Technology("GENETIC_THERAPY",ZERO_RESOURCES,GENETIC_ENGINEERING,BIOSIMULATIONS);
		TREE[GRAVITON_COLLECTOR]=new Technology("GRAVITON_COLLECTOR",ZERO_RESOURCES,QUANTUM_GRAVITY_THEORY);
		TREE[GRAVITON_DETECTOR]=new Technology("GRAVITON_DETECTOR",ZERO_RESOURCES,HIGGS_BOSON_DETECTOR);

		TREE[HADRON_COLLECTOR]=new Technology("HADRON_COLLECTOR",ZERO_RESOURCES,PHOTON_COLLECTOR,STARDUST_GATHERING);
		TREE[HEAVY_NUCLEAR_FUSION]=new Technology("HEAVY_NUCLEAR_FUSION",ZERO_RESOURCES,NUCLEAR_FUSION);
		TREE[HIGGS_BOSON_DETECTOR]=new Technology("HIGGS_BOSON_DETECTOR",ZERO_RESOURCES,SUPERCONDUCTORS);
		TREE[HUMAN_LIKE_AI]=new Technology("HUMAN_LIKE_AI",ZERO_RESOURCES,SENTIENT_AI);

		TREE[INTERGALACTIC_COLONIZATION]=new Technology("INTERGALACTIC_COLONIZATION",ZERO_RESOURCES,GAIA,NEUTRINO_DRIVE,PERFECT_MILITARY_ALGORITHMS);
		TREE[INTERSTELLAR_PHILOSOPHY]=new Technology("INTERSTELLAR_PHILOSOPHY",ZERO_RESOURCES,RELIGIOUS_TOLERANCE);
		TREE[INVISIBILITY]=new Technology("INVISIBILITY",ZERO_RESOURCES,ADVANCED_NUMERICAL_ANALYSIS,ANTI_PHOTON_SHIELDS,PHOTON_COMPUTERS);

		TREE[LEPTON_COLLECTOR]=new Technology("LEPTON_COLLECTOR",ZERO_RESOURCES,HADRON_COLLECTOR);
		TREE[LONGEVITY]=new Technology("LONGEVITY",ZERO_RESOURCES,GENETIC_THERAPY,ADVANCED_BIOLOGY,XENOECOLOGY);

		TREE[MATHEMATICAL_ETHICS]=new Technology("MATHEMATICAL_ETHICS",ZERO_RESOURCES,ADVANCED_ABSTRACT_ALGEBRA,INTERSTELLAR_PHILOSOPHY);
		TREE[MESON_COLLECTOR]=new Technology("MESON_COLLECTOR",ZERO_RESOURCES,HADRON_COLLECTOR);
		TREE[MILITARY_ALGORITHMS]=new Technology("MILITARY_ALGORITHMS",ZERO_RESOURCES);
		TREE[MULTIDIMENSIONAL_UNIFICATION_THEORY]=new Technology("MULTIDIMENSIONAL_UNIFICATION_THEORY",ZERO_RESOURCES,QUANTUM_GRAVITY_THEORY);

		TREE[NANOBOTS]=new Technology("NANOBOTS",ZERO_RESOURCES,ADVANCED_NANOSTRUCTURES);
		TREE[NEUTRINO_COLLECTOR]=new Technology("NEUTRINO_COLLECTOR",ZERO_RESOURCES,LEPTON_COLLECTOR);
		TREE[NEUTRINO_DRIVE]=new Technology("NEUTRINO_DRIVE",ZERO_RESOURCES,ADVANCED_NEUTRINO_GUN,INVISIBILITY,COUNTER_NEUTRINO_GUN);
		TREE[NEUTRINO_GUN]=new Technology("NEUTRINO_GUN",ZERO_RESOURCES,ADVANCED_LASERS,NEUTRINO_COLLECTOR);
		TREE[NEUTRINO_TELESCOPE]=new Technology("NEUTRINO_TELESCOPE",ZERO_RESOURCES,NEUTRINO_COLLECTOR,SUBATOMIC_PHOTON_DETECTOR);
		TREE[NUCLEAR_FUSION]=new Technology("NUCLEAR_FUSION",ZERO_RESOURCES,SUPERCONDUCTORS);

		TREE[PERFECT_HEAT_DIFFUSION]=new Technology("PERFECT_HEAT_DIFFUSION",ZERO_RESOURCES,ENGINEERING_SINGULARITY,QUICK_HEAT_DIFFUSION);
		TREE[PERFECT_HEAT_RADIATION]=new Technology("PERFECT_HEAT_RADIATION",ZERO_RESOURCES,ENGINEERING_SINGULARITY,QUICK_HEAT_RADIATION);
		TREE[PERFECT_MILITARY_ALGORITHMS]=new Technology("PERFECT_MILITARY_ALGORITHMS",ZERO_RESOURCES,ADVANCED_MILITARY_ALGORITHMS,ENGINEERING_SINGULARITY,PLANETARY_DEFENSE);
		TREE[PHOTON_BALLISTICS]=new Technology("PHOTON_BALLISTICS",ZERO_RESOURCES,ADVANCED_NUMERICAL_ANALYSIS,MILITARY_ALGORITHMS);
		TREE[PHOTON_COLLECTOR]=new Technology("PHOTON_COLLECTOR",ZERO_RESOURCES,ADVANCED_CHEMISTRY);
		TREE[PHOTON_COMPUTERS]=new Technology("PHOTON_COMPUTERS",ZERO_RESOURCES,QUANTUM_CRYPTOGRAPHY);
		TREE[PLANETARY_DEFENSE]=new Technology("PLANETARY_DEFENSE",ZERO_RESOURCES,ANTI_PHOTON_SHIELDS,PHOTON_BALLISTICS);
		TREE[PLANETLESS_COLONIES]=new Technology("PLANETLESS_COLONIES",ZERO_RESOURCES,ADVANCED_AGRICULTURE,ASTEROID_MINING,TERRAFORMING);
		TREE[PORTABLE_NUCLEAR_FUSION]=new Technology("PORTABLE_NUCLEAR_FUSION",ZERO_RESOURCES,HADRON_COLLECTOR,NUCLEAR_FUSION);

		TREE[QUANTUM_AI]=new Technology("QUANTUM_AI",ZERO_RESOURCES,HUMAN_LIKE_AI,QUANTUM_COMPUTERS);
		TREE[QUANTUM_COMPUTERS]=new Technology("QUANTUM_COMPUTERS",ZERO_RESOURCES,ADVANCED_NANOSTRUCTURES,SILICON_SUPERCOMPUTERS);
		TREE[QUANTUM_CRYPTOGRAPHY]=new Technology("QUANTUM_CRYPTOGRAPHY",ZERO_RESOURCES,SILICON_SUPERCOMPUTERS);
		TREE[QUANTUM_ETHICS]=new Technology("QUANTUM_ETHICS",ZERO_RESOURCES,MULTIDIMENSIONAL_UNIFICATION_THEORY,QUANTUM_AI,SOLVED_ETHICS);
		TREE[QUANTUM_GOVERNMENT]=new Technology("QUANTUM_GOVERNMENT",ZERO_RESOURCES,AI_GOVERNMENT,QUANTUM_AI);
		TREE[QUANTUM_GRAVITY_THEORY]=new Technology("QUANTUM_GRAVITY_THEORY",ZERO_RESOURCES,LEPTON_COLLECTOR,MESON_COLLECTOR,NEUTRINO_COLLECTOR,RIGOROUS_SCIENCE);
		TREE[QUICK_HEAT_DIFFUSION]=new Technology("QUICK_HEAT_DIFFUSION",ZERO_RESOURCES,ADVANCED_ALLOYS,SUPERCONDUCTORS);
		TREE[QUICK_HEAT_RADIATION]=new Technology("QUICK_HEAT_RADIATION",ZERO_RESOURCES,FRACTAL_MATERIALS);

		TREE[RELIGIOUS_TOLERANCE]=new Technology("RELIGIOUS_TOLERANCE",ZERO_RESOURCES);
		TREE[RIGOROUS_SCIENCE]=new Technology("RIGOROUS_SCIENCE",ZERO_RESOURCES);
		TREE[ROBOCULTURE]=new Technology("ROBOCULTURE",ZERO_RESOURCES,HUMAN_LIKE_AI,INTERSTELLAR_PHILOSOPHY);
		TREE[ROBOETHICS]=new Technology("ROBOETHICS",ZERO_RESOURCES,SENTIENT_AI);
		TREE[ROBOTIC_COLONIES]=new Technology("ROBOTIC_COLONIES",ZERO_RESOURCES,AI_GOVERNMENT,PLANETLESS_COLONIES,ROBOCULTURE);

		TREE[SCIENTIFICAL_SINGULARITY]=new Technology("SCIENTIFICAL_SINGULARITY",ZERO_RESOURCES,ENGINEERING_SINGULARITY,MULTIDIMENSIONAL_UNIFICATION_THEORY);
		TREE[SENTIENT_AI]=new Technology("SENTIENT_AI",ZERO_RESOURCES,SILICON_SUPERCOMPUTERS);
		TREE[SILICON_SUPERCOMPUTERS]=new Technology("SILICON_SUPERCOMPUTERS",ZERO_RESOURCES);
		TREE[SOLVED_ETHICS]=new Technology("SOLVED_ETHICS",ZERO_RESOURCES,MATHEMATICAL_ETHICS,ROBOETHICS,SUPERSTITION_ERADICATION);
		TREE[STARDUST_GATHERING]=new Technology("STARDUST_GATHERING",ZERO_RESOURCES,ASTEROID_MINING);
		TREE[SUBATOMIC_PHOTON_DETECTOR]=new Technology("SUBATOMIC_PHOTON_DETECTOR",ZERO_RESOURCES,PHOTON_COLLECTOR);
		TREE[SUPERCONDUCTORS]=new Technology("SUPERCONDUCTORS",ZERO_RESOURCES);
		TREE[SUPERSTITION_ERADICATION]=new Technology("SUPERSTITION_ERADICATION",ZERO_RESOURCES,RIGOROUS_SCIENCE);

		TREE[TERRAFORMING]=new Technology("TERRAFORMING",ZERO_RESOURCES,CLIMATE_MANIPULATION,GENETIC_ENGINEERING);

		TREE[UNIVERSAL_CURE]=new Technology("UNIVERSAL_CURE",ZERO_RESOURCES,ADVANCED_BIOLOGY,GENETIC_THERAPY,NANOBOTS);
		
		TREE[XENOECOLOGY]=new Technology("XENOECOLOGY",ZERO_RESOURCES,BIOSIMULATIONS);

	}
}
